import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAgentJobsTable1769913983449 implements MigrationInterface {
    name = 'CreateAgentJobsTable1769913983449'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_4a7c584ddfe855379598b5e20fd"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_4e83431119fa585fc7aa8b817db"`);
        await queryRunner.query(`ALTER TABLE "backup_codes" DROP CONSTRAINT "FK_backup_codes_user"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_450ec5d913fb7b44f7d441b83fe"`);
        await queryRunner.query(`ALTER TABLE "workspaces" DROP CONSTRAINT "FK_552b8a0813f929c0d369c5f7ff7"`);
        await queryRunner.query(`ALTER TABLE "workspace_settings" DROP CONSTRAINT "fk_workspace_settings_workspace"`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" DROP CONSTRAINT "FK_cf5df369b7a86ea3cdf18c7b56d"`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" DROP CONSTRAINT "FK_5e77cd15920476ed768ec51da45"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_9b4b555ca01bd035b4879ed4fce"`);
        await queryRunner.query(`ALTER TABLE "shared_links" DROP CONSTRAINT "FK_shared_links_project"`);
        await queryRunner.query(`ALTER TABLE "shared_links" DROP CONSTRAINT "FK_shared_links_workspace"`);
        await queryRunner.query(`ALTER TABLE "shared_links" DROP CONSTRAINT "FK_shared_links_user"`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" DROP CONSTRAINT "fk_provisioning_status_project"`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" DROP CONSTRAINT "fk_provisioning_status_workspace"`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" DROP CONSTRAINT "FK_c0cf6efc6f60b9f1546a86ced00"`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" DROP CONSTRAINT "FK_7186de31cff5502b7ff7a3dc16c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_workspace_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "byok_secrets" DROP CONSTRAINT "fk_byok_secrets_created_by"`);
        await queryRunner.query(`ALTER TABLE "api_usage" DROP CONSTRAINT "fk_api_usage_workspace"`);
        await queryRunner.query(`ALTER TABLE "api_usage" DROP CONSTRAINT "fk_api_usage_project"`);
        await queryRunner.query(`ALTER TABLE "api_usage" DROP CONSTRAINT "fk_api_usage_byok_key"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workspace_members_workspace_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workspace_members_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_backup_codes_user_id_used"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_deleted_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_current_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workspace_settings_limit_enabled"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workspace_invitations_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workspace_invitations_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workspace_invitations_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workspace_invitations_workspace_email_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_usage_tracking_workspace_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_usage_tracking_workspace_project_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_project_preferences_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_created_by_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_workspace_id_name_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shared_links_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shared_links_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shared_links_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shared_links_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shared_links_token_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SECURITY_EVENTS_USER_EVENT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SECURITY_EVENTS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SECURITY_EVENTS_IP"`);
        await queryRunner.query(`DROP INDEX "public"."idx_onboarding_status_user_workspace_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_onboarding_status_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_onboarding_status_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_workspace_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_unread"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_byok_secrets_workspace_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_account_deletions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_account_deletions_scheduled_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_account_deletions_completed"`);
        await queryRunner.query(`DROP INDEX "public"."idx_account_deletions_original_email"`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" DROP CONSTRAINT "chk_provisioning_status_valid"`);
        await queryRunner.query(`ALTER TABLE "api_usage" DROP CONSTRAINT "chk_api_usage_provider"`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "user_id" uuid NOT NULL, "action" character varying(100) NOT NULL, "resource_type" character varying(50) NOT NULL, "resource_id" character varying(255) NOT NULL, "metadata" jsonb, "ip_address" character varying(45), "user_agent" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_59dbb15b4dffc1edfe68f91ff5" ON "audit_logs" ("workspace_id", "action") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b541c08baef2ec8cd6716885b" ON "audit_logs" ("workspace_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d04b6f2b05825501c1427f0d9" ON "audit_logs" ("resource_type", "resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_46a2bc82e4d3575f85cb44c4f3" ON "audit_logs" ("workspace_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "workspace_members" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "backup_codes" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workspaces" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workspaces" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workspace_settings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workspace_settings" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shared_links" ADD CONSTRAINT "UQ_80da78f4c80173edf51ab10b4a0" UNIQUE ("token")`);
        await queryRunner.query(`ALTER TABLE "security_events" DROP COLUMN "event_type"`);
        await queryRunner.query(`CREATE TYPE "public"."security_events_event_type_enum" AS ENUM('login_success', 'login_failed', 'logout', '2fa_enabled', '2fa_disabled', '2fa_verified', '2fa_failed', 'password_changed', 'password_change_failed', 'account_deleted', 'account_deletion_failed', 'rate_limit_hit', 'token_revoked', 'session_created', 'session_deleted', 'anomaly_detected', 'workspace_created', 'workspace_creation_failed', 'workspace_deleted', 'workspace_switched', 'invitation_created', 'invitation_accepted', 'invitation_revoked', 'permission_denied', 'role_changed', 'member_removed', 'ownership_transferred')`);
        await queryRunner.query(`ALTER TABLE "security_events" ADD "event_type" "public"."security_events_event_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "security_events" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "metadata" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "byok_secrets" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "byok_secrets" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_usage_workspace_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_usage_project_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_usage_byok_key"`);
        await queryRunner.query(`ALTER TABLE "api_usage" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "account_deletions" ALTER COLUMN "original_email" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "account_deletions" ALTER COLUMN "deleted_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_d1149b6d47b8878fcf45216f28" ON "backup_codes" ("user_id", "used") `);
        await queryRunner.query(`CREATE INDEX "IDX_073999dfec9d14522f0cf58cd6" ON "users" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_450ec5d913fb7b44f7d441b83f" ON "users" ("current_workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d45c409f17dfc2d44d4b5e7fa" ON "workspace_invitations" ("workspace_id", "email", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_efb7ba588916737f408a72a3cc" ON "workspace_invitations" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ac6b6f3385aaa08effc8bc206" ON "workspace_invitations" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf5df369b7a86ea3cdf18c7b56" ON "workspace_invitations" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e7b206e13d3c39e990d7ca3e3" ON "usage_tracking" ("workspace_id", "project_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_45319930d085f373aca002899c" ON "usage_tracking" ("workspace_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b4b555ca01bd035b4879ed4fc" ON "projects" ("created_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_af78b8fc6857fe0a10d1bb1699" ON "projects" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_177d06dc85ccfe3bc729d38d75" ON "projects" ("workspace_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff81a79487343b20006cc2962b" ON "shared_links" ("token", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_185ffb32218991392c71c74a15" ON "shared_links" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7800cfb244b0611e20bf558d3" ON "shared_links" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a491724e1d11b609cec6093ab" ON "shared_links" ("project_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_80da78f4c80173edf51ab10b4a" ON "shared_links" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_87c998073af994bb49340be58c" ON "security_events" ("ip_address") `);
        await queryRunner.query(`CREATE INDEX "IDX_d86aa84090327c9a94aee62e18" ON "security_events" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c873234e7d7239ccaae62779a" ON "security_events" ("user_id", "event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_7186de31cff5502b7ff7a3dc16" ON "onboarding_status" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0cf6efc6f60b9f1546a86ced0" ON "onboarding_status" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fdc723d22e2f133a443925db02" ON "onboarding_status" ("user_id", "workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_77ee7b06d6f802000c0846f3a5" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_8385e7e4b0c91cfa308cba3f13" ON "notifications" ("workspace_id", "user_id", "read_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_91fa0aebab77f3ac7568a364da" ON "notifications" ("workspace_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6a7862de27e1711830e028eb3" ON "byok_secrets" ("workspace_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_api_usage_byok_key" ON "api_usage" ("byok_key_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_api_usage_project_date" ON "api_usage" ("project_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_api_usage_workspace_date" ON "api_usage" ("workspace_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b895a73cfec502e6f6ac3034a6" ON "account_deletions" ("original_email") `);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_4a7c584ddfe855379598b5e20fd" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_4e83431119fa585fc7aa8b817db" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backup_codes" ADD CONSTRAINT "FK_70066ea80d2f4b871beda32633b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_450ec5d913fb7b44f7d441b83fe" FOREIGN KEY ("current_workspace_id") REFERENCES "workspaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD CONSTRAINT "FK_552b8a0813f929c0d369c5f7ff7" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_settings" ADD CONSTRAINT "FK_c51a656a68d78e78ad782165950" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" ADD CONSTRAINT "FK_cf5df369b7a86ea3cdf18c7b56d" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" ADD CONSTRAINT "FK_5e77cd15920476ed768ec51da45" FOREIGN KEY ("inviter_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_9b4b555ca01bd035b4879ed4fce" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_links" ADD CONSTRAINT "FK_6a491724e1d11b609cec6093ab4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_links" ADD CONSTRAINT "FK_c7800cfb244b0611e20bf558d3d" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_links" ADD CONSTRAINT "FK_093c2bc5dee11e2847c0c70fa1f" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" ADD CONSTRAINT "FK_34676e0d2fc7512f5cccade5427" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" ADD CONSTRAINT "FK_4235aa156c78441d7837ae6a68d" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" ADD CONSTRAINT "FK_c0cf6efc6f60b9f1546a86ced00" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" ADD CONSTRAINT "FK_7186de31cff5502b7ff7a3dc16c" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_ff8a9bf1b558104a843964c01ec" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "byok_secrets" ADD CONSTRAINT "FK_f0fc94dd732461e470c4ee45cea" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_usage" ADD CONSTRAINT "FK_27cf0492200be25a8d836da6ed7" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_usage" ADD CONSTRAINT "FK_4e99f9873e02f7cce18bbfc9c73" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_usage" ADD CONSTRAINT "FK_3a1d1c29fd71be0cf5dfbc4dd68" FOREIGN KEY ("byok_key_id") REFERENCES "byok_secrets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "api_usage" DROP CONSTRAINT "FK_3a1d1c29fd71be0cf5dfbc4dd68"`);
        await queryRunner.query(`ALTER TABLE "api_usage" DROP CONSTRAINT "FK_4e99f9873e02f7cce18bbfc9c73"`);
        await queryRunner.query(`ALTER TABLE "api_usage" DROP CONSTRAINT "FK_27cf0492200be25a8d836da6ed7"`);
        await queryRunner.query(`ALTER TABLE "byok_secrets" DROP CONSTRAINT "FK_f0fc94dd732461e470c4ee45cea"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_ff8a9bf1b558104a843964c01ec"`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" DROP CONSTRAINT "FK_7186de31cff5502b7ff7a3dc16c"`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" DROP CONSTRAINT "FK_c0cf6efc6f60b9f1546a86ced00"`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" DROP CONSTRAINT "FK_4235aa156c78441d7837ae6a68d"`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" DROP CONSTRAINT "FK_34676e0d2fc7512f5cccade5427"`);
        await queryRunner.query(`ALTER TABLE "shared_links" DROP CONSTRAINT "FK_093c2bc5dee11e2847c0c70fa1f"`);
        await queryRunner.query(`ALTER TABLE "shared_links" DROP CONSTRAINT "FK_c7800cfb244b0611e20bf558d3d"`);
        await queryRunner.query(`ALTER TABLE "shared_links" DROP CONSTRAINT "FK_6a491724e1d11b609cec6093ab4"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_9b4b555ca01bd035b4879ed4fce"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e"`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" DROP CONSTRAINT "FK_5e77cd15920476ed768ec51da45"`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" DROP CONSTRAINT "FK_cf5df369b7a86ea3cdf18c7b56d"`);
        await queryRunner.query(`ALTER TABLE "workspace_settings" DROP CONSTRAINT "FK_c51a656a68d78e78ad782165950"`);
        await queryRunner.query(`ALTER TABLE "workspaces" DROP CONSTRAINT "FK_552b8a0813f929c0d369c5f7ff7"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_450ec5d913fb7b44f7d441b83fe"`);
        await queryRunner.query(`ALTER TABLE "backup_codes" DROP CONSTRAINT "FK_70066ea80d2f4b871beda32633b"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_4e83431119fa585fc7aa8b817db"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_4a7c584ddfe855379598b5e20fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b895a73cfec502e6f6ac3034a6"`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_usage_workspace_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_usage_project_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_api_usage_byok_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6a7862de27e1711830e028eb3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91fa0aebab77f3ac7568a364da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8385e7e4b0c91cfa308cba3f13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77ee7b06d6f802000c0846f3a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fdc723d22e2f133a443925db02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0cf6efc6f60b9f1546a86ced0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7186de31cff5502b7ff7a3dc16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c873234e7d7239ccaae62779a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d86aa84090327c9a94aee62e18"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87c998073af994bb49340be58c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80da78f4c80173edf51ab10b4a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a491724e1d11b609cec6093ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7800cfb244b0611e20bf558d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_185ffb32218991392c71c74a15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff81a79487343b20006cc2962b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_177d06dc85ccfe3bc729d38d75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af78b8fc6857fe0a10d1bb1699"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b4b555ca01bd035b4879ed4fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45319930d085f373aca002899c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e7b206e13d3c39e990d7ca3e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf5df369b7a86ea3cdf18c7b56"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ac6b6f3385aaa08effc8bc206"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_efb7ba588916737f408a72a3cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d45c409f17dfc2d44d4b5e7fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_450ec5d913fb7b44f7d441b83f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_073999dfec9d14522f0cf58cd6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1149b6d47b8878fcf45216f28"`);
        await queryRunner.query(`ALTER TABLE "account_deletions" ALTER COLUMN "deleted_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "account_deletions" ALTER COLUMN "original_email" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "api_usage" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX "idx_api_usage_byok_key" ON "api_usage" ("byok_key_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_api_usage_project_date" ON "api_usage" ("project_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_api_usage_workspace_date" ON "api_usage" ("workspace_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "byok_secrets" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "byok_secrets" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "metadata" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "security_events" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "security_events" DROP COLUMN "event_type"`);
        await queryRunner.query(`DROP TYPE "public"."security_events_event_type_enum"`);
        await queryRunner.query(`ALTER TABLE "security_events" ADD "event_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shared_links" DROP CONSTRAINT "UQ_80da78f4c80173edf51ab10b4a0"`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workspace_settings" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workspace_settings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workspaces" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workspaces" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "backup_codes" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46a2bc82e4d3575f85cb44c4f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d04b6f2b05825501c1427f0d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b541c08baef2ec8cd6716885b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59dbb15b4dffc1edfe68f91ff5"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`ALTER TABLE "api_usage" ADD CONSTRAINT "chk_api_usage_provider" CHECK (((provider)::text = ANY ((ARRAY['anthropic'::character varying, 'openai'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" ADD CONSTRAINT "chk_provisioning_status_valid" CHECK ((status = ANY (ARRAY['pending'::provisioning_status_status_enum, 'in_progress'::provisioning_status_status_enum, 'completed'::provisioning_status_status_enum, 'failed'::provisioning_status_status_enum])))`);
        await queryRunner.query(`CREATE INDEX "idx_account_deletions_original_email" ON "account_deletions" ("original_email") `);
        await queryRunner.query(`CREATE INDEX "IDX_account_deletions_completed" ON "account_deletions" ("completed") `);
        await queryRunner.query(`CREATE INDEX "IDX_account_deletions_scheduled_at" ON "account_deletions" ("hard_delete_scheduled_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_account_deletions_user_id" ON "account_deletions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_byok_secrets_workspace_active" ON "byok_secrets" ("workspace_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_created_at" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_unread" ON "notifications" ("workspace_id", "user_id", "read_at") WHERE (read_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_notifications_workspace_user" ON "notifications" ("workspace_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_onboarding_status_workspace_id" ON "onboarding_status" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "idx_onboarding_status_user_id" ON "onboarding_status" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_onboarding_status_user_workspace_unique" ON "onboarding_status" ("user_id", "workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_SECURITY_EVENTS_IP" ON "security_events" ("ip_address") `);
        await queryRunner.query(`CREATE INDEX "IDX_SECURITY_EVENTS_CREATED_AT" ON "security_events" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_SECURITY_EVENTS_USER_EVENT" ON "security_events" ("user_id", "event_type") `);
        await queryRunner.query(`CREATE INDEX "idx_shared_links_token_active" ON "shared_links" ("token", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_shared_links_is_active" ON "shared_links" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_shared_links_workspace_id" ON "shared_links" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shared_links_project_id" ON "shared_links" ("project_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_shared_links_token" ON "shared_links" ("token") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_projects_workspace_id_name_unique" ON "projects" ("name", "workspace_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_created_by_user_id" ON "projects" ("created_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_workspace_id" ON "projects" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_project_preferences_project_id" ON "project_preferences" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_usage_tracking_workspace_project_date" ON "usage_tracking" ("workspace_id", "project_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_usage_tracking_workspace_date" ON "usage_tracking" ("workspace_id", "date") `);
        await queryRunner.query(`CREATE INDEX "idx_workspace_invitations_workspace_email_status" ON "workspace_invitations" ("workspace_id", "email", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_workspace_invitations_token" ON "workspace_invitations" ("token") `);
        await queryRunner.query(`CREATE INDEX "idx_workspace_invitations_email" ON "workspace_invitations" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_workspace_invitations_workspace_id" ON "workspace_invitations" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "idx_workspace_settings_limit_enabled" ON "workspace_settings" ("limit_enabled") WHERE (limit_enabled = true)`);
        await queryRunner.query(`CREATE INDEX "idx_users_current_workspace_id" ON "users" ("current_workspace_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_deleted_at" ON "users" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_backup_codes_user_id_used" ON "backup_codes" ("user_id", "used") `);
        await queryRunner.query(`CREATE INDEX "idx_workspace_members_role" ON "workspace_members" ("role") `);
        await queryRunner.query(`CREATE INDEX "idx_workspace_members_workspace_user" ON "workspace_members" ("workspace_id", "user_id") `);
        await queryRunner.query(`ALTER TABLE "api_usage" ADD CONSTRAINT "fk_api_usage_byok_key" FOREIGN KEY ("byok_key_id") REFERENCES "byok_secrets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_usage" ADD CONSTRAINT "fk_api_usage_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_usage" ADD CONSTRAINT "fk_api_usage_workspace" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "byok_secrets" ADD CONSTRAINT "fk_byok_secrets_created_by" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" ADD CONSTRAINT "FK_7186de31cff5502b7ff7a3dc16c" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "onboarding_status" ADD CONSTRAINT "FK_c0cf6efc6f60b9f1546a86ced00" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" ADD CONSTRAINT "fk_provisioning_status_workspace" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provisioning_status" ADD CONSTRAINT "fk_provisioning_status_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_links" ADD CONSTRAINT "FK_shared_links_user" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_links" ADD CONSTRAINT "FK_shared_links_workspace" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_links" ADD CONSTRAINT "FK_shared_links_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_9b4b555ca01bd035b4879ed4fce" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" ADD CONSTRAINT "FK_5e77cd15920476ed768ec51da45" FOREIGN KEY ("inviter_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_invitations" ADD CONSTRAINT "FK_cf5df369b7a86ea3cdf18c7b56d" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_settings" ADD CONSTRAINT "fk_workspace_settings_workspace" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD CONSTRAINT "FK_552b8a0813f929c0d369c5f7ff7" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_450ec5d913fb7b44f7d441b83fe" FOREIGN KEY ("current_workspace_id") REFERENCES "workspaces"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backup_codes" ADD CONSTRAINT "FK_backup_codes_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_4e83431119fa585fc7aa8b817db" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_4a7c584ddfe855379598b5e20fd" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
