/**
 * Planner Agent Execution Interfaces
 * Story 11.6: Planner Agent CLI Integration
 *
 * Defines types and interfaces for the Planner Agent pipeline execution,
 * including execution params/results, document types, sprint status types,
 * progress events, and step progress constants.
 */

// ─── Planner Task Type ──────────────────────────────────────────────────────

/**
 * Types of planning tasks the Planner Agent can perform.
 */
export type PlannerTaskType =
  | 'create-project-plan'
  | 'breakdown-epic'
  | 'create-stories'
  | 'generate-prd'
  | 'generate-architecture';

// ─── Planner Agent Execution Params ─────────────────────────────────────────

/**
 * Parameters required to execute a full planning cycle.
 * Passed from PipelineJobHandler to PlannerAgentPipelineExecutor.
 */
export interface PlannerAgentExecutionParams {
  workspaceId: string;
  projectId: string;
  storyId: string | null;
  projectName: string;
  projectDescription: string;
  projectGoals: string[];
  epicId: string | null;
  epicDescription: string | null;
  planningTask: PlannerTaskType;
  techStack: string;
  codeStylePreferences: string;
  templateType: string | null;
  workspacePath: string;
  gitRepoUrl: string;
  githubToken: string;
  repoOwner: string;
  repoName: string;
  existingEpics: string[];
  existingStories: string[];
  previousPlannerOutput: string | null;
}

// ─── Planner Agent Execution Result ─────────────────────────────────────────

/**
 * Result returned after a planner agent execution completes.
 * Includes document info, story entries, commit info, and timing.
 */
export interface PlannerAgentExecutionResult {
  success: boolean;
  planningTask: PlannerTaskType;
  documentsGenerated: PlannerDocument[];
  storiesCreated: PlannerStoryEntry[];
  commitHash: string | null;
  sessionId: string;
  durationMs: number;
  error: string | null;
}

// ─── Planner Document ───────────────────────────────────────────────────────

/**
 * A planning document generated by the Planner Agent.
 */
export interface PlannerDocument {
  type:
    | 'product-brief'
    | 'prd'
    | 'architecture'
    | 'epic'
    | 'story'
    | 'sprint-status';
  filePath: string;
  title: string;
}

// ─── Planner Story Entry ────────────────────────────────────────────────────

/**
 * A story entry generated by the Planner Agent for sprint-status.yaml.
 */
export interface PlannerStoryEntry {
  storyId: string;
  title: string;
  epicId: string;
  status: 'backlog' | 'ready-for-dev';
  acceptanceCriteria: string[];
  estimatedComplexity: 'S' | 'M' | 'L' | 'XL';
}

// ─── Planner Document Validation ────────────────────────────────────────────

/**
 * Result of validating all generated planning documents.
 */
export interface PlannerDocumentValidation {
  valid: boolean;
  documents: PlannerDocumentCheckResult[];
  totalDocuments: number;
  validDocuments: number;
  issues: string[];
}

/**
 * Validation result for a single planning document.
 */
export interface PlannerDocumentCheckResult {
  filePath: string;
  documentType: string;
  valid: boolean;
  hasAcceptanceCriteria: boolean;
  hasTaskBreakdown: boolean;
  issues: string[];
}

// ─── Sprint Status Types ────────────────────────────────────────────────────

/**
 * Result of updating sprint-status.yaml with new story entries.
 */
export interface SprintStatusUpdateResult {
  success: boolean;
  storiesAdded: number;
  storiesSkipped: number;
  updatedFilePath: string;
  error: string | null;
}

/**
 * Parsed representation of sprint-status.yaml.
 */
export interface ParsedSprintStatus {
  epics: Map<string, string>;
  stories: Map<string, { status: string; comment: string }>;
}

// ─── Planner Agent Progress Event ───────────────────────────────────────────

/**
 * Progress event emitted during planner agent execution.
 * Sent to workspace WebSocket room for real-time UI updates.
 */
export interface PlannerAgentProgressEvent {
  type: 'planner-agent:progress';
  sessionId: string;
  projectId: string;
  workspaceId: string;
  step: PlannerAgentStep;
  status: 'started' | 'completed' | 'failed';
  details: string;
  timestamp: Date;
}

// ─── Planner Agent Step ─────────────────────────────────────────────────────

/**
 * Steps in the planner agent execution pipeline.
 * Each step reports estimated completion percentage.
 */
export type PlannerAgentStep =
  | 'reading-project-context'
  | 'preparing-workspace'
  | 'spawning-cli'
  | 'generating-documents'
  | 'validating-documents'
  | 'updating-sprint-status'
  | 'staging-files'
  | 'committing-documents'
  | 'pushing-to-remote'
  | 'updating-status';

/**
 * Estimated completion percentage for each planner agent step.
 */
export const PLANNER_AGENT_STEP_PROGRESS: Record<PlannerAgentStep, number> = {
  'reading-project-context': 5,
  'preparing-workspace': 10,
  'spawning-cli': 15,
  'generating-documents': 55,
  'validating-documents': 65,
  'updating-sprint-status': 75,
  'staging-files': 80,
  'committing-documents': 85,
  'pushing-to-remote': 90,
  'updating-status': 100,
};
